apiVersion: apps/v1
kind: Deployment
metadata:
  name: greencart-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greencart-backend
  template:
    metadata:
      labels:
        app: greencart-backend
    spec:
      containers:
        - name: backend
          image: lakshyakumar70/greencart-backend
          ports:
            - containerPort: 4000
          env:
            - name: MONGO_URI
              value: mongodb://admin:password@mongo:27017/greencart?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: greencart-backend
spec:
  selector:
    app: greencart-backend
  ports:
    - port: 4000
      targetPort: 4000
  type: ClusterIP
